todo:
  autoAssign: true
  keyword: [
    "@PROBLEM",
    "@IDEA",
    "@IMPORTANT"
  ]
  bodyKeyword: [
    "@BODY"
  ]
  blobLines: false
  caseSensitive: false
  label: [],
  reopenClosed: true
  exclude: null
