// Generated by https://quicktype.io

export interface V1SimulatorConfiguration {
  name?: string;
  prey: V1AnimalSpecie;
  predator: V1AnimalSpecie;
  plant: V1PlantSpecie;
  size: number;
  scale: number;
  offsetX: number;
  offsetY: number;
  speed: number;
  seed: number;
  nbOfAnimalsSnapshotInterval: number;
}

export interface V1PlantSpecie {
  startingNb: number;
  spawnRate: number;
  spawnInterval: number;
}

export interface V1AnimalSpecie {
  name: string;
  startingNb: number;
  genes: V1Gene[];
}

export interface V1Gene {
  displayName: string;
  name: string;
  modificator: V1Modificator;
  avg?: number;
  stdDev?: number;
  displayValue: string;
  value?: number;
  adjustments?: V1Adjustments;
}

export interface V1Adjustments {
  [key: string]: string;
}

export enum V1Modificator {
  Constant = "constant",
  Stddev = "stddev",
}
