import type { SimulatorConfiguration } from "../types/simulator-configuration";

export const baseConfiguration: SimulatorConfiguration = {
  version: "2",

  id: "0",
  title: "",
  seed: 0,
  mapSideSize: 8000,

  species: {
    prey: {
      exists: false,
      startingNumber: 1,
      genes: {
        speed: {
          modificator: "constant",
          value: 0,
          average: 0,
          standardDeviation: 0,
          adjustments: {
            numberOfBabies: 0,
            intervalBetweenReproductionPeriods: 0,
            viewDistance: 0,
            longevity: 0,
            amountOfFoodToEat: 0,
            timeToEat: 0,
          },
        },
        numberOfBabies: {
          modificator: "constant",
          value: 0,
          average: 0,
          standardDeviation: 0,
          adjustments: {
            speed: 0,
            intervalBetweenReproductionPeriods: 0,
            viewDistance: 0,
            longevity: 0,
            amountOfFoodToEat: 0,
            timeToEat: 0,
          },
        },
        intervalBetweenReproductionPeriods: {
          modificator: "constant",
          value: 0,
          average: 0,
          standardDeviation: 0,
          adjustments: {
            speed: 0,
            numberOfBabies: 0,
            viewDistance: 0,
            longevity: 0,
            amountOfFoodToEat: 0,
            timeToEat: 0,
          },
        },
        viewDistance: {
          modificator: "constant",
          value: 0,
          average: 0,
          standardDeviation: 0,
          adjustments: {
            speed: 0,
            numberOfBabies: 0,
            intervalBetweenReproductionPeriods: 0,
            longevity: 0,
            amountOfFoodToEat: 0,
            timeToEat: 0,
          },
        },
        longevity: {
          modificator: "constant",
          value: 0,
          average: 0,
          standardDeviation: 0,
          adjustments: {
            speed: 0,
            numberOfBabies: 0,
            intervalBetweenReproductionPeriods: 0,
            viewDistance: 0,
            amountOfFoodToEat: 0,
            timeToEat: 0,
          },
        },
        amountOfFoodToEat: {
          modificator: "constant",
          value: 0,
          average: 0,
          standardDeviation: 0,
          adjustments: {
            speed: 0,
            numberOfBabies: 0,
            intervalBetweenReproductionPeriods: 0,
            viewDistance: 0,
            longevity: 0,
            timeToEat: 0,
          },
        },
        timeToEat: {
          modificator: "constant",
          value: 0,
          average: 0,
          standardDeviation: 0,
          adjustments: {
            speed: 0,
            numberOfBabies: 0,
            intervalBetweenReproductionPeriods: 0,
            viewDistance: 0,
            longevity: 0,
            amountOfFoodToEat: 0,
          },
        },
      },
    },

    predator: {
      exists: false,
      startingNumber: 1,
      genes: {
        speed: {
          modificator: "constant",
          value: 0,
          average: 0,
          standardDeviation: 0,
          adjustments: {
            numberOfBabies: 0,
            intervalBetweenReproductionPeriods: 0,
            viewDistance: 0,
            longevity: 0,
            amountOfFoodToEat: 0,
            timeToEat: 0,
          },
        },
        numberOfBabies: {
          modificator: "constant",
          value: 0,
          average: 0,
          standardDeviation: 0,
          adjustments: {
            speed: 0,
            intervalBetweenReproductionPeriods: 0,
            viewDistance: 0,
            longevity: 0,
            amountOfFoodToEat: 0,
            timeToEat: 0,
          },
        },
        intervalBetweenReproductionPeriods: {
          modificator: "constant",
          value: 0,
          average: 0,
          standardDeviation: 0,
          adjustments: {
            speed: 0,
            numberOfBabies: 0,
            viewDistance: 0,
            longevity: 0,
            amountOfFoodToEat: 0,
            timeToEat: 0,
          },
        },
        viewDistance: {
          modificator: "constant",
          value: 0,
          average: 0,
          standardDeviation: 0,
          adjustments: {
            speed: 0,
            numberOfBabies: 0,
            intervalBetweenReproductionPeriods: 0,
            longevity: 0,
            amountOfFoodToEat: 0,
            timeToEat: 0,
          },
        },
        longevity: {
          modificator: "constant",
          value: 0,
          average: 0,
          standardDeviation: 0,
          adjustments: {
            speed: 0,
            numberOfBabies: 0,
            intervalBetweenReproductionPeriods: 0,
            viewDistance: 0,
            amountOfFoodToEat: 0,
            timeToEat: 0,
          },
        },
        amountOfFoodToEat: {
          modificator: "constant",
          value: 0,
          average: 0,
          standardDeviation: 0,
          adjustments: {
            speed: 0,
            numberOfBabies: 0,
            intervalBetweenReproductionPeriods: 0,
            viewDistance: 0,
            longevity: 0,
            timeToEat: 0,
          },
        },
        timeToEat: {
          modificator: "constant",
          value: 0,
          average: 0,
          standardDeviation: 0,
          adjustments: {
            speed: 0,
            numberOfBabies: 0,
            intervalBetweenReproductionPeriods: 0,
            viewDistance: 0,
            longevity: 0,
            amountOfFoodToEat: 0,
          },
        },
      },
    },

    plant: {
      exists: false,
      startingNumber: 0,
      spawnAmount: 0,
      spawnInterval: 1,
    },
  },
};
