# Ce dossier est utilisé pour afficher ce projet sur mon site web (https://smartineau.me)
# This folder is used to display this project on my website (https://smartineau.me)
titre = "Simulateur d'évolution selon Darwin"
etiquettes = []
dossier = "expo-sciences"
url_site_web = "https://simulateur-evolution-darwin.netlify.app"
contenu = "/README.md"
date_de_creation = 2020-06-17T19:38:54.380Z
